### ISSUE TITLE
support for column names with spaces

### ISSUE THREAD

**Issue by bhenderson** [kriasoft/knex-types#10]
Hey, I have a view where column names have spaces. I know this isn't ideal, but is there a way to support this in the generated type definition?

**Comment by koistya** [comment]
@bhenderson  Yep, it should be a small fix [here](https://github.com/kriasoft/knex-types/blob/9084cddd09f09e69f0b3d9e8f9746a3d5f88df0a/main.ts#L181) (removing spaces with an underscore). If you can send a PR with that tweak that would be awesome!
