### ISSUE TITLE
possible use for a suffix option?

### ISSUE THREAD

**Issue by bhenderson** [kriasoft/knex-types#5]
I wanted to wrap the types in a namespace, so I set the prefix to be `namespace DB {` but I needed a closing `}`. I ended up just using `fs` to write it to the file, but I'm wondering if this would be a good use case for adding a suffix option.

By the way, I'm new to typings in javascript, but having the namespace made it so I didn't have to import the file to use any of the table definitions.

**Comment by koistya** [comment]
Or, `declare global { ... }`. Yeah, that can be useful.

**Comment by bhenderson** [comment]
I implemented the suffix option because I think it's more flexible. But it's your lib, let me know if you prefer the global option.
